language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpcap-dev zlib1g-dev
install: ./autogen.sh
script:
  - ./configure
  - make dist
  - tar zxvf *.tar.gz
  - cd packetq-[0-9]*
  - mkdir build
  - cd build
  - ../configure
  - make
  - make test
  - src/packetq -v
